name: Backend Pipe

on:
  push:
    paths:
        - 'backend/**'
        - '.github/workflows/backend.yml'

permissions:
  checks: write
  contents: read
  packages: write

defaults:
  run:
    working-directory: backend

jobs:
  gradle-build:
    name: assemble app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 25

    - uses: gradle/actions/setup-gradle@v5

    - name: Test & Build
      run: ./gradlew build

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: always()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
        include_passed: true

  docker-build:
    name: build & push image
    runs-on: ubuntu-latest
    needs: gradle-build
    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 25

    - uses: gradle/actions/setup-gradle@v5
        
    - name: Build & Publish Docker Image
      run: |
        ./gradlew bootBuildImage \
          --imageName=ghcr.io/edikwalta/playground-be:${{ github.sha }} \
          --publishRegistry=ghcr.io \
          --publishUsername=${{ github.actor }} \
          --publishPassword=${{ secrets.GITHUB_TOKEN }}